#Criando uma lista
lista = ("Arroz", "Feijão", "Açúcar", "Farinha", "Óleo")
#imprimindo a lista
print(lista)
#Criando uma lista
lista = ("Arroz", "Feijão", "Açúcar", "Farinha", "Óleo")
#acessando um elemento da lista polo índice
print("item : ", lista [0])
print("item : ", lista [1])
print("item : ", lista [2])
print("item : ", lista [3])
print("item : ", lista [4])
lista = ("Arroz", "Feijão", "Açúcar", "Farinha", "Óleo")
#acessando um elemento da lista polo índice e atualizando o seu valor
lista [3] = "Café"